# Generated by Django 4.2.2 on 2024-04-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='adc04a56d93bfdedf85ef3e1a8871339', max_length=50, verbose_name='Токен'),
            preserve_default=False,
        ),
    ]
