# Generated by Django 4.2.2 on 2024-04-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_client_user_message_user_settingsmailing_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingsmailing',
            name='clients',
        ),
        migrations.AddField(
            model_name='settingsmailing',
            name='clients',
            field=models.ManyToManyField(related_name='clients_mailing', to='mailings.client', verbose_name='клиенты рассылки'),
        ),
    ]
