# Generated by Django 4.2.2 on 2024-04-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0004_alter_settingsmailing_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmailing',
            name='start_time',
            field=models.DateTimeField(verbose_name='время начала'),
        ),
    ]
