# Generated by Django 4.2.2 on 2024-04-18 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0005_alter_settingsmailing_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='settingsmailing',
            old_name='user',
            new_name='owner',
        ),
    ]
