# Generated by Django 4.2.2 on 2024-04-19 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0006_rename_user_client_owner_rename_user_message_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settingsmailing',
            options={'permissions': [('set_is_activated', 'Может менять активность рассылки')], 'verbose_name': 'Настройки рассылки', 'verbose_name_plural': 'Настройки рассылок'},
        ),
    ]
